config/routes.rb
Rails.application.routes.draw do
  
  #get 'users/index'

  devise_for :users, :controllers => { registrations: 'registrations' }  

  root to: 'pages#home'
  get 'menu'       => 'pages#menu'
  get 'directory'  => 'users#index'
  get 'info'       => 'pages#info'
  get 'shops'      => 'users#index'
  #match '/users',   to: 'users#index',   via: 'get'
  #get 'users/:id' => 'users#show', as: :user
  get 'users/:user_name' => 'users#show', as: :user
  resources :sections,    :only => [:new, :create, :edit, :update, :destroy]
  resources :items,       :only => [:new, :create, :edit, :update, :destroy]
  resources :users,       :only => [:show]
  resources :restaurants, :only => [:new, :create, :edit, :update]
  resources :schedules,   :only => [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sections, dependent: :destroy
  has_many :items, dependent: :destroy
  has_one  :restaurant, dependent: :destroy
  has_one  :schedule, dependent: :destroy

  validates :user_name, presence: true, length: {minimum: 4, maximum: 16}
  validates_uniqueness_of :user_name

  if Rails.env.development?
    def self.search(search)
      if search
        q = "%#{search}%"

        joins(:restaurant).where("users.user_name LIKE ? OR 
                                 restaurants.name LIKE ? OR
                                 restaurants.category LIKE ? OR
                                 restaurants.zip_code LIKE ? OR
                                 restaurants.state LIKE ? OR
                                 restaurants.city LIKE ?",q, q, q, q, q, q)
      end
    end
  end
  if Rails.env.production?
    def self.search(search)
      if search
        q = "%#{search}%"

        joins(:restaurant).where("users.user_name ILIKE ? OR 
                                 restaurants.name ILIKE ? OR
                                 restaurants.category ILIKE ? OR
                                 restaurants.zip_code ILIKE ? OR
                                 restaurants.state ILIKE ? OR
                                 restaurants.city ILIKE ?",q, q, q, q, q, q)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    else
      @users = User.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    #@user = User.find(params[:id])
    @user = User.find_by(user_name: params[:user_name])
    @sections = @user.sections
    @items = @user.items
    @restaurant = @user.restaurant;
    @schedule = @user.schedule;
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_ajax_dropdown.html.erb
<option value = "<%=section.id%>"><%= section.name %></option>

app/views/users/_ajax_item.html.erb
  <div class="item design-item" id="item_<%= item.id %>">
    <div class="item-name item-<%= item.id%>-name" onclick="extraItemInfo(<%= item.id%>)"><%= item.name %></div>
    <div class="item-price"><%= item.price %></div>
    <br class='clearfix'/>
    <div class="item-line-seperator"></div>
    <% unless item.item_picture.blank? %>
      <div class="item-picture item-<%= item.id%>-picture">
        <% picId = item.name + ' image' %>
        <%= link_to( image_tag(item.item_picture.small_pic), image_url(item.item_picture.medium_pic), class: "fancybox", id: picId, rel: "gallery1", title: item.name) %>
      </div>
    <% end %>
    <div class="item-description item-<%= item.id%>-description"><%= item.description %></div>
    <% unless item.ingredients.empty? %>
    <div class="item-ingredients item-<%= item.id%>-ingredients">Ingredients: <%= item.ingredients %></div>
    <% end %>
    <br class="clearfix">
      <div>
        <%= link_to item, remote: true, data: {confirm: "Are you sure?"},  method: :delete do %>
          <div class="delete-item item-action-button">
            <i class="fa fa-trash-o"></i>
          </div>
        <% end %>
      </div>
      <div>
        <%= render :partial => 'partials/item_modals/edit_item_modal', :locals => {:@itemEdit => item} %>
      </div>
      <br></br>
  </div>

app/views/users/_ajax_item_picture.html.erb
<% unless item.item_picture.blank? %>
  <div class="item-image-container">
    <div class="image item-<%=item.id%>-image">
      <% picId = item.name + ' image' %>
      <%= link_to( image_tag(item.item_picture.small_pic), image_url(item.item_picture.medium_pic), class: "fancybox", id: picId, rel: "gallery1", title: item.name) %>
    </div>
  </div>
<% end %>

app/views/users/_ajax_section.html.erb
<div id="<%= section.id%>-section-and-items" class="section_and_items">
  <%= render :partial => 'users/section', :locals => {:section => section, :@sections => sections} %>
  <div id="<%= section.id%>-item-list">
    <ul class="items">
      <!-- Put Items here -->
    </ul>
  </div>
</div>

app/views/users/_item.html.erb
<% if item.section_id == section.id %>
  <div class="item <% if current_user == @user %>design-item<% end %>" id="item_<%= item.id %>">
    <div class="item-name item-<%= item.id%>-name" onclick="extraItemInfo(<%= item.id%>)"><%= item.name %></div>
    <div class="item-price"><%= item.price %></div>
    <br class='clearfix'/>
    <div class="item-line-seperator"></div>
    <% unless item.item_picture.blank? %>
      <div class="item-picture item-<%= item.id%>-picture">
        <% picId = item.name + ' image' %>
        <%= link_to( image_tag(item.item_picture.small_pic), image_url(item.item_picture.medium_pic), class: "fancybox", id: picId, rel: "gallery1", title: item.name) %>
      </div>
    <% end %>
    <div class="item-description item-<%= item.id%>-description"><%= item.description %></div>
    <% unless item.ingredients.empty? %>
    <div class="item-ingredients item-<%= item.id%>-ingredients">Ingredients: <%= item.ingredients %></div>
    <% end %>
    <br class="clearfix">

    <% if current_user == @user %>
      <div>
        <%= link_to item, remote: true, data: {confirm: "Are you sure?"},  method: :delete do %>
          <div class="delete-item item-action-button">
            <i class="fa fa-trash-o"></i>
          </div>
        <% end %>
      </div>
      <div>
        <%= render :partial => 'partials/item_modals/edit_item_modal', :locals => {:@itemEdit => item} %>
      </div>
      <br></br>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<div class="store-search-form">
<%= form_tag(shops_path, :method => "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
    <%= button_tag(type: "submit", :name => nil, :class => "search-button") do %>
    <i class="fa fa-search"></i>
    <% end %>
    <% if false %>
    <%= submit_tag "Search", :name => nil %>
    <% end %>
<% end %>

</div>

<% if @users.blank? %>
  <h4>There are no restaurants containing the term <%= params[:search] %>.</h4>
<% end %>

app/views/users/_section.html.erb
<div class="section">
  <ul id="section-<%=section.id%>">
    <li class="section-name">
      <div class="section-name-<%=section.id%>"><%= section.name %></div>
    </li>
    <% if current_user == @user && current_user != nil %>
      <li>
        <%= link_to section, remote: true, data: {confirm: "Are you sure?"}, method: :delete do %>
          <div class="delete-section section-action-button">
            <i class="fa fa-trash-o"></i>
          </div>
        <% end %>
      </li>
      <li>
        <%= render :partial => 'partials/section_modals/edit_section_modal', :locals => {:sectionEdit => section, :sections => @sections} %>
      </li>
      <li>
        <%= render :partial => 'partials/item_modals/new_item_modal', :locals =>{:@itemNew => current_user.items.build, :section => section} %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<% provide :title, "Store Directory" %>
<div class="directory-title">
  <h1>Store Directory</h1>
</div>
<div class="store-search">
  <%= render 'users/search' %>
</div>
<br class="clearfix">
<div class="page-container">
  <div class="restaurant-list">
    <ul>
      <% @users.each do |user| %>
        <%= link_to user_path(user.user_name) do %>
          <li>
            <div class="restaurant-image">
              <%= image_tag user.restaurant.restaurant_picture.small_pic %>
            </div>
            <div class="restaurant-name">
              <%= user.restaurant.name %>
            </div>
            <div class="restaurant-address">
              <%= user.restaurant.street_number %>
              <%= user.restaurant.street_name %>
              <br>
              <%= user.restaurant.city %>
              <%= user.restaurant.zip_code %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  
  <div class="pagination">
  <%= will_paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @restaurant.name) %>
<div class="store-header">
  <div class="upper-half">
    <h1 class="store-name"><%= @restaurant.name %></h1>
  </div>
  <div class="halves-break halves-break-expand"></div>
  <div class="lower-half">
    <div class="store-pic-row">
      <div class="store-profile-pic-column">
        <div class="profile-pic" style="background-image: url(<%= @restaurant.restaurant_picture.small_pic %>); ">
        </div>
      </div>
    </div>
    <div class="store-info-row">
      <div class="store-address-column">
        <div class="store-address">
          <%= render 'restaurants/store_info' %>
        </div>
      </div>
      <div class="store-description-column">
        <div class="description">
          <%= render 'restaurants/store_description' %>
        </div>
      </div>
      <div class="schedule-column">
        <%= render 'schedules/schedule' %>
      </div>
    </div>
  </div>
</div>
<div class="page-container">
  <div class="menu-and-gallery-row">
    <div class="menu-column">
      <div class="menu-create-buttons">
        <% if current_user == @user && current_user!= nil %>
        <%= render :partial => 'partials/section_modals/new_section_modal', :locals => {:@sectionNew => current_user.sections.build, :sections => @sections} %>
        <% end %>
      </div>
      <section class="menu">
        <div class="sections-list">
          <% @sections.each do |section| %>
          <div id="<%= section.id%>-section-and-items" class="section_and_items">
            <%= render :partial => 'users/section', :locals => {:section => section} %>
            <div id="<%= section.id%>-item-list">
              <ul class="items">
                <% @items.each do |item| %>
                  <%= render :partial => 'users/item', :locals => {:item => item, :section =>section} %>
                <% end %>
              </ul>
            </div>
          </div>
          <% end %>
        </div>
      </section>
    </div>
    <section class="gallery-column">
      <%= render :partial => 'items/gallery' %>
    </section>
  </div>
  <section class="store-contact-row">
    <%= render 'restaurants/contact_links' %>
  </section>
</div>