config/routes.rb
Rails.application.routes.draw do
  
  #get 'users/index'

  devise_for :users, :controllers => { registrations: 'registrations' }  

  root to: 'pages#home'
  get 'menu'       => 'pages#menu'
  get 'directory'  => 'users#index'
  get 'info'       => 'pages#info'
  get 'shops'      => 'users#index'
  #match '/users',   to: 'users#index',   via: 'get'
  #get 'users/:id' => 'users#show', as: :user
  get 'users/:user_name' => 'users#show', as: :user
  resources :sections,    :only => [:new, :create, :edit, :update, :destroy]
  resources :items,       :only => [:new, :create, :edit, :update, :destroy]
  resources :users,       :only => [:show]
  resources :restaurants, :only => [:new, :create, :edit, :update]
  resources :schedules,   :only => [:new, :create, :edit, :update]
end

app/views/partials/user_session/_log_in_modal.html.erb
<div id="login-modal" class="modal">
  <div class="modal-trigger">
    <div class="registration-button login-button">
      <label for="modal-2">
        Log In
      </label>
    </div>
  </div>
  <input class="modal-state" id="modal-2" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="modal-2"></div>
      <fieldset class="form-fields-container">
      <legend>Log in</legend>
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
      <% if devise_mapping.rememberable? -%>
      <div class="field">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
      <% end -%>
      <div class="actions">
        <%= f.submit "Log in" %>
      </div>
      <% end %>
      </fieldset>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

app/views/partials/user_session/_sign_up_modal.html.erb
<div id="signup-modal" class="modal">
  <div class="modal-trigger">
    <div class="registration-button signup-button">
      <label for="modal-1">
        Sign Up
      </label>
    </div>
  </div>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="modal-1"></div>
      <fieldset class="form-fields-container">
        <legend>Sign up</legend>
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
        <div class="field">
          <%= f.label :user_name %><br/>
          <%= f.text_field :user_name %>
        </div>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>
        <div class="actions">
          <%= f.submit "Sign up" %>
        </div>
        <% end %>
        </fieldset>
    <%= render "devise/shared/links" %>

    </div>
  </div>
</div>