config/routes.rb
Rails.application.routes.draw do
  
  #get 'users/index'

  devise_for :users, :controllers => { registrations: 'registrations' }  

  root to: 'pages#home'
  get 'menu'       => 'pages#menu'
  get 'directory'  => 'users#index'
  get 'info'       => 'pages#info'
  get 'shops'      => 'users#index'
  #match '/users',   to: 'users#index',   via: 'get'
  #get 'users/:id' => 'users#show', as: :user
  get 'users/:user_name' => 'users#show', as: :user
  resources :sections,    :only => [:new, :create, :edit, :update, :destroy]
  resources :items,       :only => [:new, :create, :edit, :update, :destroy]
  resources :users,       :only => [:show]
  resources :restaurants, :only => [:new, :create, :edit, :update]
  resources :schedules,   :only => [:new, :create, :edit, :update]
end

app/views/pages/gallery.html.erb
<% provide(:title, "Gallery") %>
<h1>Pages#gallery</h1>
<p>Find me in app/views/pages/gallery.html.erb</p>

app/views/pages/home.html.erb
<section id="banner">
  <div>
    <% if user_signed_in?%>
    <% if @user.restaurant.blank? %>
    <div class="message">
      Next step is to fill out the form in <%= link_to "Store Info", new_restaurant_path %>
    </div>
    <% end %>
    <% if @user.schedule.blank? && @user.restaurant.blank? == false %>
    <div class="message">
      Next Fill in <%= link_to "Schedule", new_schedule_path %>
    </div>
    <% end %>
    <% end %>
    <div id="js-parallax-window" class="parallax-window">
      <div class="parallax-static-content">
        <h1 id="title">
        <span class="name-first-half">simply</span><span class="name-second-half">Eat</span>
        </h1>
        <p>Show off only the essentials</p>
        <% if !(user_signed_in?) %>
        <div class="registration-partial-signup">
          <%= render 'partials/user_session/sign_up_modal' %>
        </div>
        <div class="registration-partial-login">
          <%= render 'partials/user_session/log_in_modal' %>
        </div>
        <% end %>
      </div>
      <div id="js-parallax-background" class="parallax-background"></div>
    </div>
  </div>
</section>

<section class="problem-and-solution">
  <div class="problem">
    <h3>
      Only the essentials...
    </h3>
    <p>Potential customers only want the info to get your food in their stomachs. The <span>where</span>, the <span>when</span>, the <span>what</span>.</p>
  </div>
  <div class="solutions page-container">
    <div class = "solution">
      <div class="solution-pic">
        <%= image_tag "location.svg" %>
      </div>
      <div class="solution-text">
      <h3>Your Place</h3>
        <p>
          Let potential customers easily find where you are
        </p>
      </div>
    </div>
    <div class = "solution">
      <div class="solution-pic">
        <%= image_tag "time.svg" %>
      </div>
      <div class="solution-text">
      <h3>Your Time</h3>
        <p>
          Use an easily changeable schedule to update at any time
        </p>
      </div>
    </div>
    <div class = "solution">
      <div class="solution-pic">
        <%= image_tag "drink.svg" %>
      </div>
      <div class="solution-text">
      <h3>Your Food</h3>
        <p>
          Show off your cuisine with a dynamic menu and a compact photo gallery
        </p>
      </div>
    </div>
  </div>
</section>
<section class = "menu-demo">
  <div class="menu-demo-title">
    Quickly add items to your online menu in 3 easy steps
  </div>
  <div class="menu-interaction">
      <div class="steps-container">
      <div class="steps">
        <div class="step-flex" id="step1" onclick="stepSelect(1, this)">
          <div class="step first-step">
            <i class="fa fa-pencil"></i>Fill Out Info
          </div>
        </div>
        <div class="step-flex" id="step2" onclick="stepSelect(2, this)">
          <div class="step">
            <i class="fa fa-camera"></i>Snap a Picture
          </div>
        </div>
        <div class="step-flex" id="step3" onclick="stepSelect(3, this)">
          <div class="step">
            <i class="fa fa-cutlery"></i>Create!
          </div>
        </div>
      </div>
    </div>
    <div class="menu-interaction-graphic-container">
      <div class="image-container">
        <%= image_tag 'form.png' %>
      </div>
    </div>
  </div>
</section>